### PR TITLE
Add eslint to project

### PR DESCRIPTION
**Pull request by alogan519**
Add eslint to project and remove 'use strict' directives from eslint errors
Fix indentation of for loop

### CODE REVIEW

**Comment by alogan519** [comment]
!set-reviewers @mpharoah-d2l

**Comment by mpharoah-d2l** [comment]
Why did the `'use strict';` lines have to be removed? If it's just ESLint complaining, you can either add an exception to `.eslintrc` (or include the strictify package, and use it to automatically add the `'use strict';` lines after linting has already been done)

**Comment by alogan519** [comment]
it looks like babel is readding it back to the js files in /dist. I'll look into it a bit more, this is one of the rules from the Brightspace eslint rules... says it's unnecessary inside of modules.

**Comment by mpharoah-d2l** [comment]
:+1:

**Comment by alogan519** [comment]
!set-reviewers @mpharoah-d2l @dbatiste

**Pull request merged**
