### PR TITLE
Enhanced to include additional props to enable usage as a checked menu list

### PR DESCRIPTION
**Pull request by mdgbayly**
This was my attempt to enhance this component to support our needs as a checked menu list.

I adopted a hands-off approach where most of checkbox type functionality is managed by the application through setting appropriate styles and aria attributes on this component.
The changes mostly involve allowing the injection of additional props to achieve the required behaviour.

Let me know what you think. 

1. Included additional span tag in each list item to act as an image placeholder which can be styled with css.
2. Added support for configurable props for each list item so that you can include aria properties like aria-checked to enable accessible menuitemcheckboxes.
3. Added support for configurable menu props to allowing adding menu aria properties.
4. Added an autoClose prop which can be set to false to avoid the menu closing automatically when items are selected.
5. Fixed a bug with the SPACE key causing scrolling when selecting items
6. Added key props where appropriate to avoid React warnings

### CODE REVIEW

**Comment by dbatiste** [comment]
Hey Martin - to be honest, I think the component should implement the semantics and behavior that goes with it.  I don't have any big concerns with exposing a way to add props - I just don't think the code for adding the semantics and behavior belongs in the application in this case.  I know some refactoring may be necessary to make that possible in this component, and some additional data would be expected for items in order to make it work.  The current React component API isn't ideal for extending in the way we'd like for this...

@dlockhart and I are in the midst of implementing some dropdown functionality that will be consumed by menu-item WCs and their variants.  The intent is that specific components will be implemented to provide this functionality (one of which being `d2l-dropdown-checkbox-menu` and will be configured to use auto-close on a more generic component that can easily be consumed for different purposes).

That being said, I see this component becoming deprecated and I don't foresee any/many further enhancements being made to it.

Another option here may be: fork this repo with this solution so you can move forward, with the intent of adopting the WC solution when it's ready.  Thoughts?

**Comment by mdgbayly** [comment]
Yeh, I would generally agree with your comments about incorporating the semantics and behaviour into the component.  However, I don't think it's necessarily the case that all state like the checked state of the menu items should be managed by the component.  In our case the checked state of the menu items represents application state and that application state is used in different areas of the application. The check mark in the menu item is just one rendering of that state.

That said, I took the hands-off, minimalist approach for this because the expectation is that somewhere down the line we'll be switching this over to web components and I didn't want to invest a lot of time and effort in enhancing this component if it was going to be throw away.

I'm ok with forking it but it does raise the question of where that fork should live.  It's forked to my own github account at the moment which doesn't seem like a great medium term solution.  I guess if someone else on my team needs to further extend it and I fall under a bus they can just fork it to their account.  I think it would be confusing to fork to the Brightspace org so I wouldn't advocate that. 

I had hoped that the changes were innocuous enough that you'd be ok accepting the PR particularly if there are no plans to further extend this component?  But I'm OK with it if you are not comfortable with that.  We'll just live with the private fork for now.

Cheers

**Comment by mdgbayly** [comment]
I also recognise that there is work for you in just accepting the PR... due diligence/versions/work/worry you'd probably rather not have - so another reason why i'm OK if we just leave it as a user fork...

**Comment by dbatiste** [comment]
Hey Martin, yeah that's generally how I feel about it too (the changes to support the props aren't a big concern for this component itself).

**Pull request closed without merging**
